Repository vinaykomaravolu/vplayer, pull requests merged in 2021-05, with the labels that each got.

#22 Frontend/settings
  package-lock.json
  package.json
  src/app/App.global.css
  src/app/App.tsx
  src/app/components/MusicPlayer.tsx
  src/app/components/Nav.tsx
  src/app/components/temp.txt
  src/app/pages/Home.tsx
  src/app/pages/Player.tsx
  src/app/pages/Playlists.tsx
  src/app/pages/Settings.tsx
  src/electron/index.html
  src/package-lock.json
  tailwind.config.js
  yarn.lock
Labels: enhancement, frontend

#25 Frontend/musicplayerui
  src/app/components/MusicPlayer.tsx
Labels: frontend

#29 Fixes package production white screen
  src/electron/index.html
  src/electron/main.dev.ts
  src/electron/main.prod.js
Labels: bug
